DROP TABLE IF EXISTS Pages CASCADE;
CREATE TABLE Pages (id SERIAL PRIMARY KEY, url VARCHAR NOT NULL, is_scraping BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
DROP TABLE IF EXISTS Links;
CREATE TABLE Links (id SERIAL PRIMARY KEY, page_id INTEGER, url VARCHAR NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (page_id) REFERENCES Pages(id));
